/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Equipment,
  EquipmentCreate,
  EquipmentPage,
  EquipmentStatus,
  EquipmentUpdate,
} from '../models';
import {
    EquipmentFromJSON,
    EquipmentToJSON,
    EquipmentCreateFromJSON,
    EquipmentCreateToJSON,
    EquipmentPageFromJSON,
    EquipmentPageToJSON,
    EquipmentStatusFromJSON,
    EquipmentStatusToJSON,
    EquipmentUpdateFromJSON,
    EquipmentUpdateToJSON,
} from '../models';

export interface CreateEquipmentRequest {
    equipmentCreate: EquipmentCreate;
}

export interface DecommissionEquipmentRequest {
    equipmentId: string;
}

export interface GetEquipmentRequest {
    equipmentId: string;
}

export interface ListEquipmentRequest {
    page?: number;
    pageSize?: number;
    status?: EquipmentStatus;
    type?: string;
    locationId?: string;
}

export interface UpdateEquipmentRequest {
    equipmentId: string;
    equipmentUpdate: EquipmentUpdate;
}

/**
 * EquipmentApi - interface
 * 
 * @export
 * @interface EquipmentApiInterface
 */
export interface EquipmentApiInterface {
    /**
     * Registers a new piece of equipment in the inventory.
     * @summary Create equipment
     * @param {EquipmentCreate} equipmentCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApiInterface
     */
    createEquipmentRaw(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Registers a new piece of equipment in the inventory.
     * Create equipment
     */
    createEquipment(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

    /**
     * Marks equipment as decommissioned (soft delete). Equipment with open service requests cannot be decommissioned.
     * @summary Decommission equipment
     * @param {string} equipmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApiInterface
     */
    decommissionEquipmentRaw(requestParameters: DecommissionEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Marks equipment as decommissioned (soft delete). Equipment with open service requests cannot be decommissioned.
     * Decommission equipment
     */
    decommissionEquipment(requestParameters: DecommissionEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get equipment
     * @param {string} equipmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApiInterface
     */
    getEquipmentRaw(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Get equipment
     */
    getEquipment(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

    /**
     * Returns a paginated list of equipment. Supports filtering by status, type, and location.
     * @summary List equipment
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {EquipmentStatus} [status] 
     * @param {string} [type] 
     * @param {string} [locationId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApiInterface
     */
    listEquipmentRaw(requestParameters: ListEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentPage>>;

    /**
     * Returns a paginated list of equipment. Supports filtering by status, type, and location.
     * List equipment
     */
    listEquipment(requestParameters: ListEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentPage>;

    /**
     * Full update of equipment fields.
     * @summary Update equipment
     * @param {string} equipmentId 
     * @param {EquipmentUpdate} equipmentUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApiInterface
     */
    updateEquipmentRaw(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>>;

    /**
     * Full update of equipment fields.
     * Update equipment
     */
    updateEquipment(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment>;

}

/**
 * 
 */
export class EquipmentApi extends runtime.BaseAPI implements EquipmentApiInterface {

    /**
     * Registers a new piece of equipment in the inventory.
     * Create equipment
     */
    async createEquipmentRaw(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipmentCreate === null || requestParameters.equipmentCreate === undefined) {
            throw new runtime.RequiredError('equipmentCreate','Required parameter requestParameters.equipmentCreate was null or undefined when calling createEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/equipment`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentCreateToJSON(requestParameters.equipmentCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Registers a new piece of equipment in the inventory.
     * Create equipment
     */
    async createEquipment(requestParameters: CreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.createEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Marks equipment as decommissioned (soft delete). Equipment with open service requests cannot be decommissioned.
     * Decommission equipment
     */
    async decommissionEquipmentRaw(requestParameters: DecommissionEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling decommissionEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marks equipment as decommissioned (soft delete). Equipment with open service requests cannot be decommissioned.
     * Decommission equipment
     */
    async decommissionEquipment(requestParameters: DecommissionEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.decommissionEquipmentRaw(requestParameters, initOverrides);
    }

    /**
     * Get equipment
     */
    async getEquipmentRaw(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling getEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Get equipment
     */
    async getEquipment(requestParameters: GetEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.getEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of equipment. Supports filtering by status, type, and location.
     * List equipment
     */
    async listEquipmentRaw(requestParameters: ListEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentPage>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        if (requestParameters.locationId !== undefined) {
            queryParameters['locationId'] = requestParameters.locationId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/equipment`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentPageFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of equipment. Supports filtering by status, type, and location.
     * List equipment
     */
    async listEquipment(requestParameters: ListEquipmentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentPage> {
        const response = await this.listEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Full update of equipment fields.
     * Update equipment
     */
    async updateEquipmentRaw(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Equipment>> {
        if (requestParameters.equipmentId === null || requestParameters.equipmentId === undefined) {
            throw new runtime.RequiredError('equipmentId','Required parameter requestParameters.equipmentId was null or undefined when calling updateEquipment.');
        }

        if (requestParameters.equipmentUpdate === null || requestParameters.equipmentUpdate === undefined) {
            throw new runtime.RequiredError('equipmentUpdate','Required parameter requestParameters.equipmentUpdate was null or undefined when calling updateEquipment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/equipment/{equipmentId}`.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters.equipmentId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EquipmentUpdateToJSON(requestParameters.equipmentUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentFromJSON(jsonValue));
    }

    /**
     * Full update of equipment fields.
     * Update equipment
     */
    async updateEquipment(requestParameters: UpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Equipment> {
        const response = await this.updateEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
