/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EquipmentPage,
  EquipmentStatus,
  Location,
  LocationCreate,
  LocationPage,
  LocationUpdate,
} from '../models';
import {
    EquipmentPageFromJSON,
    EquipmentPageToJSON,
    EquipmentStatusFromJSON,
    EquipmentStatusToJSON,
    LocationFromJSON,
    LocationToJSON,
    LocationCreateFromJSON,
    LocationCreateToJSON,
    LocationPageFromJSON,
    LocationPageToJSON,
    LocationUpdateFromJSON,
    LocationUpdateToJSON,
} from '../models';

export interface CreateLocationRequest {
    locationCreate: LocationCreate;
}

export interface DeleteLocationRequest {
    locationId: string;
}

export interface GetLocationRequest {
    locationId: string;
}

export interface ListEquipmentAtLocationRequest {
    locationId: string;
    page?: number;
    pageSize?: number;
    status?: EquipmentStatus;
}

export interface ListLocationsRequest {
    page?: number;
    pageSize?: number;
    building?: string;
    floor?: string;
    department?: string;
}

export interface UpdateLocationRequest {
    locationId: string;
    locationUpdate: LocationUpdate;
}

/**
 * LocationsApi - interface
 * 
 * @export
 * @interface LocationsApiInterface
 */
export interface LocationsApiInterface {
    /**
     * 
     * @summary Create location
     * @param {LocationCreate} locationCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationsApiInterface
     */
    createLocationRaw(requestParameters: CreateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>>;

    /**
     * Create location
     */
    createLocation(requestParameters: CreateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location>;

    /**
     * Cannot delete a location that currently has equipment assigned to it.
     * @summary Delete location
     * @param {string} locationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationsApiInterface
     */
    deleteLocationRaw(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Cannot delete a location that currently has equipment assigned to it.
     * Delete location
     */
    deleteLocation(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get location
     * @param {string} locationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationsApiInterface
     */
    getLocationRaw(requestParameters: GetLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>>;

    /**
     * Get location
     */
    getLocation(requestParameters: GetLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location>;

    /**
     * 
     * @summary List equipment at a location
     * @param {string} locationId 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {EquipmentStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationsApiInterface
     */
    listEquipmentAtLocationRaw(requestParameters: ListEquipmentAtLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentPage>>;

    /**
     * List equipment at a location
     */
    listEquipmentAtLocation(requestParameters: ListEquipmentAtLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentPage>;

    /**
     * 
     * @summary List locations
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [building] 
     * @param {string} [floor] 
     * @param {string} [department] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationsApiInterface
     */
    listLocationsRaw(requestParameters: ListLocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationPage>>;

    /**
     * List locations
     */
    listLocations(requestParameters: ListLocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationPage>;

    /**
     * 
     * @summary Update location
     * @param {string} locationId 
     * @param {LocationUpdate} locationUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LocationsApiInterface
     */
    updateLocationRaw(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>>;

    /**
     * Update location
     */
    updateLocation(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location>;

}

/**
 * 
 */
export class LocationsApi extends runtime.BaseAPI implements LocationsApiInterface {

    /**
     * Create location
     */
    async createLocationRaw(requestParameters: CreateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>> {
        if (requestParameters.locationCreate === null || requestParameters.locationCreate === undefined) {
            throw new runtime.RequiredError('locationCreate','Required parameter requestParameters.locationCreate was null or undefined when calling createLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/locations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LocationCreateToJSON(requestParameters.locationCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationFromJSON(jsonValue));
    }

    /**
     * Create location
     */
    async createLocation(requestParameters: CreateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location> {
        const response = await this.createLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cannot delete a location that currently has equipment assigned to it.
     * Delete location
     */
    async deleteLocationRaw(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.locationId === null || requestParameters.locationId === undefined) {
            throw new runtime.RequiredError('locationId','Required parameter requestParameters.locationId was null or undefined when calling deleteLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters.locationId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cannot delete a location that currently has equipment assigned to it.
     * Delete location
     */
    async deleteLocation(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLocationRaw(requestParameters, initOverrides);
    }

    /**
     * Get location
     */
    async getLocationRaw(requestParameters: GetLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>> {
        if (requestParameters.locationId === null || requestParameters.locationId === undefined) {
            throw new runtime.RequiredError('locationId','Required parameter requestParameters.locationId was null or undefined when calling getLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters.locationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationFromJSON(jsonValue));
    }

    /**
     * Get location
     */
    async getLocation(requestParameters: GetLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location> {
        const response = await this.getLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List equipment at a location
     */
    async listEquipmentAtLocationRaw(requestParameters: ListEquipmentAtLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EquipmentPage>> {
        if (requestParameters.locationId === null || requestParameters.locationId === undefined) {
            throw new runtime.RequiredError('locationId','Required parameter requestParameters.locationId was null or undefined when calling listEquipmentAtLocation.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations/{locationId}/equipment`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters.locationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EquipmentPageFromJSON(jsonValue));
    }

    /**
     * List equipment at a location
     */
    async listEquipmentAtLocation(requestParameters: ListEquipmentAtLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EquipmentPage> {
        const response = await this.listEquipmentAtLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List locations
     */
    async listLocationsRaw(requestParameters: ListLocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationPage>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.building !== undefined) {
            queryParameters['building'] = requestParameters.building;
        }

        if (requestParameters.floor !== undefined) {
            queryParameters['floor'] = requestParameters.floor;
        }

        if (requestParameters.department !== undefined) {
            queryParameters['department'] = requestParameters.department;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationPageFromJSON(jsonValue));
    }

    /**
     * List locations
     */
    async listLocations(requestParameters: ListLocationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationPage> {
        const response = await this.listLocationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update location
     */
    async updateLocationRaw(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Location>> {
        if (requestParameters.locationId === null || requestParameters.locationId === undefined) {
            throw new runtime.RequiredError('locationId','Required parameter requestParameters.locationId was null or undefined when calling updateLocation.');
        }

        if (requestParameters.locationUpdate === null || requestParameters.locationUpdate === undefined) {
            throw new runtime.RequiredError('locationUpdate','Required parameter requestParameters.locationUpdate was null or undefined when calling updateLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/locations/{locationId}`.replace(`{${"locationId"}}`, encodeURIComponent(String(requestParameters.locationId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LocationUpdateToJSON(requestParameters.locationUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationFromJSON(jsonValue));
    }

    /**
     * Update location
     */
    async updateLocation(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Location> {
        const response = await this.updateLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
