/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Priority,
  ServiceRequest,
  ServiceRequestCreate,
  ServiceRequestPage,
  ServiceRequestStatus,
  ServiceRequestUpdate,
} from '../models';
import {
    PriorityFromJSON,
    PriorityToJSON,
    ServiceRequestFromJSON,
    ServiceRequestToJSON,
    ServiceRequestCreateFromJSON,
    ServiceRequestCreateToJSON,
    ServiceRequestPageFromJSON,
    ServiceRequestPageToJSON,
    ServiceRequestStatusFromJSON,
    ServiceRequestStatusToJSON,
    ServiceRequestUpdateFromJSON,
    ServiceRequestUpdateToJSON,
} from '../models';

export interface CreateServiceRequestRequest {
    serviceRequestCreate: ServiceRequestCreate;
}

export interface DeleteServiceRequestRequest {
    requestId: string;
}

export interface GetServiceRequestRequest {
    requestId: string;
}

export interface ListServiceRequestsRequest {
    page?: number;
    pageSize?: number;
    status?: ServiceRequestStatus;
    equipmentId?: string;
    priority?: Priority;
}

export interface UpdateServiceRequestRequest {
    requestId: string;
    serviceRequestUpdate: ServiceRequestUpdate;
}

/**
 * ServiceRequestsApi - interface
 * 
 * @export
 * @interface ServiceRequestsApiInterface
 */
export interface ServiceRequestsApiInterface {
    /**
     * Medical staff submits a new service/repair request for a piece of equipment.
     * @summary Create service request
     * @param {ServiceRequestCreate} serviceRequestCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceRequestsApiInterface
     */
    createServiceRequestRaw(requestParameters: CreateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequest>>;

    /**
     * Medical staff submits a new service/repair request for a piece of equipment.
     * Create service request
     */
    createServiceRequest(requestParameters: CreateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequest>;

    /**
     * Only NEW requests that have not been assigned can be deleted.
     * @summary Delete service request
     * @param {string} requestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceRequestsApiInterface
     */
    deleteServiceRequestRaw(requestParameters: DeleteServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Only NEW requests that have not been assigned can be deleted.
     * Delete service request
     */
    deleteServiceRequest(requestParameters: DeleteServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get service request
     * @param {string} requestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceRequestsApiInterface
     */
    getServiceRequestRaw(requestParameters: GetServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequest>>;

    /**
     * Get service request
     */
    getServiceRequest(requestParameters: GetServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequest>;

    /**
     * 
     * @summary List service requests
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {ServiceRequestStatus} [status] 
     * @param {string} [equipmentId] 
     * @param {Priority} [priority] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceRequestsApiInterface
     */
    listServiceRequestsRaw(requestParameters: ListServiceRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequestPage>>;

    /**
     * List service requests
     */
    listServiceRequests(requestParameters: ListServiceRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequestPage>;

    /**
     * Full update of service request fields including status.
     * @summary Update service request
     * @param {string} requestId 
     * @param {ServiceRequestUpdate} serviceRequestUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceRequestsApiInterface
     */
    updateServiceRequestRaw(requestParameters: UpdateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequest>>;

    /**
     * Full update of service request fields including status.
     * Update service request
     */
    updateServiceRequest(requestParameters: UpdateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequest>;

}

/**
 * 
 */
export class ServiceRequestsApi extends runtime.BaseAPI implements ServiceRequestsApiInterface {

    /**
     * Medical staff submits a new service/repair request for a piece of equipment.
     * Create service request
     */
    async createServiceRequestRaw(requestParameters: CreateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequest>> {
        if (requestParameters.serviceRequestCreate === null || requestParameters.serviceRequestCreate === undefined) {
            throw new runtime.RequiredError('serviceRequestCreate','Required parameter requestParameters.serviceRequestCreate was null or undefined when calling createServiceRequest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/service-requests`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceRequestCreateToJSON(requestParameters.serviceRequestCreate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceRequestFromJSON(jsonValue));
    }

    /**
     * Medical staff submits a new service/repair request for a piece of equipment.
     * Create service request
     */
    async createServiceRequest(requestParameters: CreateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequest> {
        const response = await this.createServiceRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Only NEW requests that have not been assigned can be deleted.
     * Delete service request
     */
    async deleteServiceRequestRaw(requestParameters: DeleteServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.requestId === null || requestParameters.requestId === undefined) {
            throw new runtime.RequiredError('requestId','Required parameter requestParameters.requestId was null or undefined when calling deleteServiceRequest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/service-requests/{requestId}`.replace(`{${"requestId"}}`, encodeURIComponent(String(requestParameters.requestId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Only NEW requests that have not been assigned can be deleted.
     * Delete service request
     */
    async deleteServiceRequest(requestParameters: DeleteServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteServiceRequestRaw(requestParameters, initOverrides);
    }

    /**
     * Get service request
     */
    async getServiceRequestRaw(requestParameters: GetServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequest>> {
        if (requestParameters.requestId === null || requestParameters.requestId === undefined) {
            throw new runtime.RequiredError('requestId','Required parameter requestParameters.requestId was null or undefined when calling getServiceRequest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/service-requests/{requestId}`.replace(`{${"requestId"}}`, encodeURIComponent(String(requestParameters.requestId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceRequestFromJSON(jsonValue));
    }

    /**
     * Get service request
     */
    async getServiceRequest(requestParameters: GetServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequest> {
        const response = await this.getServiceRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List service requests
     */
    async listServiceRequestsRaw(requestParameters: ListServiceRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequestPage>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.equipmentId !== undefined) {
            queryParameters['equipmentId'] = requestParameters.equipmentId;
        }

        if (requestParameters.priority !== undefined) {
            queryParameters['priority'] = requestParameters.priority;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/service-requests`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceRequestPageFromJSON(jsonValue));
    }

    /**
     * List service requests
     */
    async listServiceRequests(requestParameters: ListServiceRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequestPage> {
        const response = await this.listServiceRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Full update of service request fields including status.
     * Update service request
     */
    async updateServiceRequestRaw(requestParameters: UpdateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceRequest>> {
        if (requestParameters.requestId === null || requestParameters.requestId === undefined) {
            throw new runtime.RequiredError('requestId','Required parameter requestParameters.requestId was null or undefined when calling updateServiceRequest.');
        }

        if (requestParameters.serviceRequestUpdate === null || requestParameters.serviceRequestUpdate === undefined) {
            throw new runtime.RequiredError('serviceRequestUpdate','Required parameter requestParameters.serviceRequestUpdate was null or undefined when calling updateServiceRequest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/service-requests/{requestId}`.replace(`{${"requestId"}}`, encodeURIComponent(String(requestParameters.requestId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceRequestUpdateToJSON(requestParameters.serviceRequestUpdate),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceRequestFromJSON(jsonValue));
    }

    /**
     * Full update of service request fields including status.
     * Update service request
     */
    async updateServiceRequest(requestParameters: UpdateServiceRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceRequest> {
        const response = await this.updateServiceRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
