/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Equipment } from './Equipment';
import {
    EquipmentFromJSON,
    EquipmentFromJSONTyped,
    EquipmentToJSON,
} from './Equipment';

/**
 * 
 * @export
 * @interface EquipmentPage
 */
export interface EquipmentPage {
    /**
     * 
     * @type {Array<Equipment>}
     * @memberof EquipmentPage
     */
    content?: Array<Equipment>;
    /**
     * 
     * @type {number}
     * @memberof EquipmentPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentPage
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentPage
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof EquipmentPage
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the EquipmentPage interface.
 */
export function instanceOfEquipmentPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EquipmentPageFromJSON(json: any): EquipmentPage {
    return EquipmentPageFromJSONTyped(json, false);
}

export function EquipmentPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(EquipmentFromJSON)),
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function EquipmentPageToJSON(value?: EquipmentPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(EquipmentToJSON)),
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
        'page': value.page,
        'pageSize': value.pageSize,
    };
}

