/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EquipmentStatus } from './EquipmentStatus';
import {
    EquipmentStatusFromJSON,
    EquipmentStatusFromJSONTyped,
    EquipmentStatusToJSON,
} from './EquipmentStatus';

/**
 * 
 * @export
 * @interface EquipmentUpdateAllOf
 */
export interface EquipmentUpdateAllOf {
    /**
     * 
     * @type {EquipmentStatus}
     * @memberof EquipmentUpdateAllOf
     */
    status?: EquipmentStatus;
}

/**
 * Check if a given object implements the EquipmentUpdateAllOf interface.
 */
export function instanceOfEquipmentUpdateAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EquipmentUpdateAllOfFromJSON(json: any): EquipmentUpdateAllOf {
    return EquipmentUpdateAllOfFromJSONTyped(json, false);
}

export function EquipmentUpdateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentUpdateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : EquipmentStatusFromJSON(json['status']),
    };
}

export function EquipmentUpdateAllOfToJSON(value?: EquipmentUpdateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': EquipmentStatusToJSON(value.status),
    };
}

