/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EquipmentStatus } from './EquipmentStatus';
import {
    EquipmentStatusFromJSON,
    EquipmentStatusFromJSONTyped,
    EquipmentStatusToJSON,
} from './EquipmentStatus';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';

/**
 * 
 * @export
 * @interface EquipmentAllOf
 */
export interface EquipmentAllOf {
    /**
     * 
     * @type {string}
     * @memberof EquipmentAllOf
     */
    id: string;
    /**
     * 
     * @type {EquipmentStatus}
     * @memberof EquipmentAllOf
     */
    status: EquipmentStatus;
    /**
     * 
     * @type {Location}
     * @memberof EquipmentAllOf
     */
    location?: Location;
    /**
     * 
     * @type {number}
     * @memberof EquipmentAllOf
     */
    readonly openServiceRequestCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentAllOf
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentAllOf
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the EquipmentAllOf interface.
 */
export function instanceOfEquipmentAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function EquipmentAllOfFromJSON(json: any): EquipmentAllOf {
    return EquipmentAllOfFromJSONTyped(json, false);
}

export function EquipmentAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': EquipmentStatusFromJSON(json['status']),
        'location': !exists(json, 'location') ? undefined : LocationFromJSON(json['location']),
        'openServiceRequestCount': !exists(json, 'openServiceRequestCount') ? undefined : json['openServiceRequestCount'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquipmentAllOfToJSON(value?: EquipmentAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': EquipmentStatusToJSON(value.status),
        'location': LocationToJSON(value.location),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

