/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EquipmentStatus } from './EquipmentStatus';
import {
    EquipmentStatusFromJSON,
    EquipmentStatusFromJSONTyped,
    EquipmentStatusToJSON,
} from './EquipmentStatus';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';

/**
 * 
 * @export
 * @interface Equipment
 */
export interface Equipment {
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    type: string;
    /**
     * Unique inventory/asset number
     * @type {string}
     * @memberof Equipment
     */
    inventoryNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof Equipment
     */
    warrantyExpiry?: Date;
    /**
     * Current location ID
     * @type {string}
     * @memberof Equipment
     */
    locationId: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    id: string;
    /**
     * 
     * @type {EquipmentStatus}
     * @memberof Equipment
     */
    status: EquipmentStatus;
    /**
     * 
     * @type {Location}
     * @memberof Equipment
     */
    location?: Location;
    /**
     * 
     * @type {number}
     * @memberof Equipment
     */
    readonly openServiceRequestCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Equipment
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Equipment
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Equipment interface.
 */
export function instanceOfEquipment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "inventoryNumber" in value;
    isInstance = isInstance && "locationId" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function EquipmentFromJSON(json: any): Equipment {
    return EquipmentFromJSONTyped(json, false);
}

export function EquipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Equipment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'inventoryNumber': json['inventoryNumber'],
        'warrantyExpiry': !exists(json, 'warrantyExpiry') ? undefined : (new Date(json['warrantyExpiry'])),
        'locationId': json['locationId'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'id': json['id'],
        'status': EquipmentStatusFromJSON(json['status']),
        'location': !exists(json, 'location') ? undefined : LocationFromJSON(json['location']),
        'openServiceRequestCount': !exists(json, 'openServiceRequestCount') ? undefined : json['openServiceRequestCount'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function EquipmentToJSON(value?: Equipment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'inventoryNumber': value.inventoryNumber,
        'warrantyExpiry': value.warrantyExpiry === undefined ? undefined : (value.warrantyExpiry.toISOString().substr(0,10)),
        'locationId': value.locationId,
        'notes': value.notes,
        'id': value.id,
        'status': EquipmentStatusToJSON(value.status),
        'location': LocationToJSON(value.location),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

