/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentBase
 */
export interface EquipmentBase {
    /**
     * 
     * @type {string}
     * @memberof EquipmentBase
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentBase
     */
    type: string;
    /**
     * Unique inventory/asset number
     * @type {string}
     * @memberof EquipmentBase
     */
    inventoryNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentBase
     */
    warrantyExpiry?: Date;
    /**
     * Current location ID
     * @type {string}
     * @memberof EquipmentBase
     */
    locationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentBase
     */
    notes?: string;
}

/**
 * Check if a given object implements the EquipmentBase interface.
 */
export function instanceOfEquipmentBase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "inventoryNumber" in value;
    isInstance = isInstance && "locationId" in value;

    return isInstance;
}

export function EquipmentBaseFromJSON(json: any): EquipmentBase {
    return EquipmentBaseFromJSONTyped(json, false);
}

export function EquipmentBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'inventoryNumber': json['inventoryNumber'],
        'warrantyExpiry': !exists(json, 'warrantyExpiry') ? undefined : (new Date(json['warrantyExpiry'])),
        'locationId': json['locationId'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function EquipmentBaseToJSON(value?: EquipmentBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'inventoryNumber': value.inventoryNumber,
        'warrantyExpiry': value.warrantyExpiry === undefined ? undefined : (value.warrantyExpiry.toISOString().substr(0,10)),
        'locationId': value.locationId,
        'notes': value.notes,
    };
}

