/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EquipmentStatus } from './EquipmentStatus';
import {
    EquipmentStatusFromJSON,
    EquipmentStatusFromJSONTyped,
    EquipmentStatusToJSON,
} from './EquipmentStatus';

/**
 * 
 * @export
 * @interface EquipmentUpdate
 */
export interface EquipmentUpdate {
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdate
     */
    type: string;
    /**
     * Unique inventory/asset number
     * @type {string}
     * @memberof EquipmentUpdate
     */
    inventoryNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof EquipmentUpdate
     */
    warrantyExpiry?: Date;
    /**
     * Current location ID
     * @type {string}
     * @memberof EquipmentUpdate
     */
    locationId: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdate
     */
    notes?: string;
    /**
     * 
     * @type {EquipmentStatus}
     * @memberof EquipmentUpdate
     */
    status?: EquipmentStatus;
}

/**
 * Check if a given object implements the EquipmentUpdate interface.
 */
export function instanceOfEquipmentUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "inventoryNumber" in value;
    isInstance = isInstance && "locationId" in value;

    return isInstance;
}

export function EquipmentUpdateFromJSON(json: any): EquipmentUpdate {
    return EquipmentUpdateFromJSONTyped(json, false);
}

export function EquipmentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'inventoryNumber': json['inventoryNumber'],
        'warrantyExpiry': !exists(json, 'warrantyExpiry') ? undefined : (new Date(json['warrantyExpiry'])),
        'locationId': json['locationId'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'status': !exists(json, 'status') ? undefined : EquipmentStatusFromJSON(json['status']),
    };
}

export function EquipmentUpdateToJSON(value?: EquipmentUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'inventoryNumber': value.inventoryNumber,
        'warrantyExpiry': value.warrantyExpiry === undefined ? undefined : (value.warrantyExpiry.toISOString().substr(0,10)),
        'locationId': value.locationId,
        'notes': value.notes,
        'status': EquipmentStatusToJSON(value.status),
    };
}

