/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorDetailsInner
 */
export interface ErrorDetailsInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorDetailsInner
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorDetailsInner
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorDetailsInner interface.
 */
export function instanceOfErrorDetailsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorDetailsInnerFromJSON(json: any): ErrorDetailsInner {
    return ErrorDetailsInnerFromJSONTyped(json, false);
}

export function ErrorDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorDetailsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': !exists(json, 'field') ? undefined : json['field'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorDetailsInnerToJSON(value?: ErrorDetailsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'message': value.message,
    };
}

