/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationAllOf
 */
export interface LocationAllOf {
    /**
     * 
     * @type {string}
     * @memberof LocationAllOf
     */
    id: string;
    /**
     * Number of active equipment items currently at this location
     * @type {number}
     * @memberof LocationAllOf
     */
    readonly equipmentCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof LocationAllOf
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof LocationAllOf
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the LocationAllOf interface.
 */
export function instanceOfLocationAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function LocationAllOfFromJSON(json: any): LocationAllOf {
    return LocationAllOfFromJSONTyped(json, false);
}

export function LocationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'equipmentCount': !exists(json, 'equipmentCount') ? undefined : json['equipmentCount'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function LocationAllOfToJSON(value?: LocationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

