/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';

/**
 * 
 * @export
 * @interface LocationPage
 */
export interface LocationPage {
    /**
     * 
     * @type {Array<Location>}
     * @memberof LocationPage
     */
    content?: Array<Location>;
    /**
     * 
     * @type {number}
     * @memberof LocationPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationPage
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationPage
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationPage
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the LocationPage interface.
 */
export function instanceOfLocationPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationPageFromJSON(json: any): LocationPage {
    return LocationPageFromJSONTyped(json, false);
}

export function LocationPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(LocationFromJSON)),
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function LocationPageToJSON(value?: LocationPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(LocationToJSON)),
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
        'page': value.page,
        'pageSize': value.pageSize,
    };
}

