/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationBase
 */
export interface LocationBase {
    /**
     * 
     * @type {string}
     * @memberof LocationBase
     */
    building: string;
    /**
     * 
     * @type {string}
     * @memberof LocationBase
     */
    floor: string;
    /**
     * 
     * @type {string}
     * @memberof LocationBase
     */
    department: string;
    /**
     * 
     * @type {string}
     * @memberof LocationBase
     */
    room: string;
    /**
     * 
     * @type {string}
     * @memberof LocationBase
     */
    description?: string;
}

/**
 * Check if a given object implements the LocationBase interface.
 */
export function instanceOfLocationBase(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "building" in value;
    isInstance = isInstance && "floor" in value;
    isInstance = isInstance && "department" in value;
    isInstance = isInstance && "room" in value;

    return isInstance;
}

export function LocationBaseFromJSON(json: any): LocationBase {
    return LocationBaseFromJSONTyped(json, false);
}

export function LocationBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'building': json['building'],
        'floor': json['floor'],
        'department': json['department'],
        'room': json['room'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function LocationBaseToJSON(value?: LocationBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'building': value.building,
        'floor': value.floor,
        'department': value.department,
        'room': value.room,
        'description': value.description,
    };
}

