/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ServiceRequest } from './ServiceRequest';
import {
    ServiceRequestFromJSON,
    ServiceRequestFromJSONTyped,
    ServiceRequestToJSON,
} from './ServiceRequest';

/**
 * 
 * @export
 * @interface ServiceRequestPage
 */
export interface ServiceRequestPage {
    /**
     * 
     * @type {Array<ServiceRequest>}
     * @memberof ServiceRequestPage
     */
    content?: Array<ServiceRequest>;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestPage
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestPage
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestPage
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestPage
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the ServiceRequestPage interface.
 */
export function instanceOfServiceRequestPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceRequestPageFromJSON(json: any): ServiceRequestPage {
    return ServiceRequestPageFromJSONTyped(json, false);
}

export function ServiceRequestPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRequestPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : ((json['content'] as Array<any>).map(ServiceRequestFromJSON)),
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function ServiceRequestPageToJSON(value?: ServiceRequestPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content === undefined ? undefined : ((value.content as Array<any>).map(ServiceRequestToJSON)),
        'totalElements': value.totalElements,
        'totalPages': value.totalPages,
        'page': value.page,
        'pageSize': value.pageSize,
    };
}

