/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Equipment } from './Equipment';
import {
    EquipmentFromJSON,
    EquipmentFromJSONTyped,
    EquipmentToJSON,
} from './Equipment';
import type { ServiceRequestStatus } from './ServiceRequestStatus';
import {
    ServiceRequestStatusFromJSON,
    ServiceRequestStatusFromJSONTyped,
    ServiceRequestStatusToJSON,
} from './ServiceRequestStatus';

/**
 * 
 * @export
 * @interface ServiceRequestAllOf
 */
export interface ServiceRequestAllOf {
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestAllOf
     */
    id: string;
    /**
     * 
     * @type {ServiceRequestStatus}
     * @memberof ServiceRequestAllOf
     */
    status: ServiceRequestStatus;
    /**
     * 
     * @type {Equipment}
     * @memberof ServiceRequestAllOf
     */
    equipment?: Equipment;
    /**
     * 
     * @type {Date}
     * @memberof ServiceRequestAllOf
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceRequestAllOf
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ServiceRequestAllOf interface.
 */
export function instanceOfServiceRequestAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function ServiceRequestAllOfFromJSON(json: any): ServiceRequestAllOf {
    return ServiceRequestAllOfFromJSONTyped(json, false);
}

export function ServiceRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': ServiceRequestStatusFromJSON(json['status']),
        'equipment': !exists(json, 'equipment') ? undefined : EquipmentFromJSON(json['equipment']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ServiceRequestAllOfToJSON(value?: ServiceRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': ServiceRequestStatusToJSON(value.status),
        'equipment': EquipmentToJSON(value.equipment),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

