/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Equipment } from './Equipment';
import {
    EquipmentFromJSON,
    EquipmentFromJSONTyped,
    EquipmentToJSON,
} from './Equipment';
import type { Priority } from './Priority';
import {
    PriorityFromJSON,
    PriorityFromJSONTyped,
    PriorityToJSON,
} from './Priority';
import type { ServiceRequestStatus } from './ServiceRequestStatus';
import {
    ServiceRequestStatusFromJSON,
    ServiceRequestStatusFromJSONTyped,
    ServiceRequestStatusToJSON,
} from './ServiceRequestStatus';

/**
 * 
 * @export
 * @interface ServiceRequest
 */
export interface ServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof ServiceRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequest
     */
    description: string;
    /**
     * 
     * @type {Priority}
     * @memberof ServiceRequest
     */
    priority: Priority;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequest
     */
    equipmentId: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequest
     */
    id: string;
    /**
     * 
     * @type {ServiceRequestStatus}
     * @memberof ServiceRequest
     */
    status: ServiceRequestStatus;
    /**
     * 
     * @type {Equipment}
     * @memberof ServiceRequest
     */
    equipment?: Equipment;
    /**
     * 
     * @type {Date}
     * @memberof ServiceRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceRequest
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ServiceRequest interface.
 */
export function instanceOfServiceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "priority" in value;
    isInstance = isInstance && "equipmentId" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function ServiceRequestFromJSON(json: any): ServiceRequest {
    return ServiceRequestFromJSONTyped(json, false);
}

export function ServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'priority': PriorityFromJSON(json['priority']),
        'equipmentId': json['equipmentId'],
        'id': json['id'],
        'status': ServiceRequestStatusFromJSON(json['status']),
        'equipment': !exists(json, 'equipment') ? undefined : EquipmentFromJSON(json['equipment']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ServiceRequestToJSON(value?: ServiceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'priority': PriorityToJSON(value.priority),
        'equipmentId': value.equipmentId,
        'id': value.id,
        'status': ServiceRequestStatusToJSON(value.status),
        'equipment': EquipmentToJSON(value.equipment),
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

