/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Equipment & Service Management API
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - `NEW` – submitted, awaiting assignment
 * - `ASSIGNED` – assigned to a technician
 * - `IN_PROGRESS` – technician is actively working on it
 * - `CLOSED` – resolved and closed
 * @export
 */
export const ServiceRequestStatus = {
    New: 'NEW',
    Assigned: 'ASSIGNED',
    InProgress: 'IN_PROGRESS',
    Closed: 'CLOSED'
} as const;
export type ServiceRequestStatus = typeof ServiceRequestStatus[keyof typeof ServiceRequestStatus];


export function ServiceRequestStatusFromJSON(json: any): ServiceRequestStatus {
    return ServiceRequestStatusFromJSONTyped(json, false);
}

export function ServiceRequestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceRequestStatus {
    return json as ServiceRequestStatus;
}

export function ServiceRequestStatusToJSON(value?: ServiceRequestStatus | null): any {
    return value as any;
}

