/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XdsInventoryApp {
    }
    interface XdsInventoryEquipmentList {
    }
    interface XdsInventoryLocationList {
    }
    interface XdsInventoryServiceList {
    }
}
declare global {
    interface HTMLXdsInventoryAppElement extends Components.XdsInventoryApp, HTMLStencilElement {
    }
    var HTMLXdsInventoryAppElement: {
        prototype: HTMLXdsInventoryAppElement;
        new (): HTMLXdsInventoryAppElement;
    };
    interface HTMLXdsInventoryEquipmentListElement extends Components.XdsInventoryEquipmentList, HTMLStencilElement {
    }
    var HTMLXdsInventoryEquipmentListElement: {
        prototype: HTMLXdsInventoryEquipmentListElement;
        new (): HTMLXdsInventoryEquipmentListElement;
    };
    interface HTMLXdsInventoryLocationListElement extends Components.XdsInventoryLocationList, HTMLStencilElement {
    }
    var HTMLXdsInventoryLocationListElement: {
        prototype: HTMLXdsInventoryLocationListElement;
        new (): HTMLXdsInventoryLocationListElement;
    };
    interface HTMLXdsInventoryServiceListElement extends Components.XdsInventoryServiceList, HTMLStencilElement {
    }
    var HTMLXdsInventoryServiceListElement: {
        prototype: HTMLXdsInventoryServiceListElement;
        new (): HTMLXdsInventoryServiceListElement;
    };
    interface HTMLElementTagNameMap {
        "xds-inventory-app": HTMLXdsInventoryAppElement;
        "xds-inventory-equipment-list": HTMLXdsInventoryEquipmentListElement;
        "xds-inventory-location-list": HTMLXdsInventoryLocationListElement;
        "xds-inventory-service-list": HTMLXdsInventoryServiceListElement;
    }
}
declare namespace LocalJSX {
    interface XdsInventoryApp {
    }
    interface XdsInventoryEquipmentList {
    }
    interface XdsInventoryLocationList {
    }
    interface XdsInventoryServiceList {
    }
    interface IntrinsicElements {
        "xds-inventory-app": XdsInventoryApp;
        "xds-inventory-equipment-list": XdsInventoryEquipmentList;
        "xds-inventory-location-list": XdsInventoryLocationList;
        "xds-inventory-service-list": XdsInventoryServiceList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xds-inventory-app": LocalJSX.IntrinsicElements["xds-inventory-app"] & JSXBase.HTMLAttributes<HTMLXdsInventoryAppElement>;
            "xds-inventory-equipment-list": LocalJSX.IntrinsicElements["xds-inventory-equipment-list"] & JSXBase.HTMLAttributes<HTMLXdsInventoryEquipmentListElement>;
            "xds-inventory-location-list": LocalJSX.IntrinsicElements["xds-inventory-location-list"] & JSXBase.HTMLAttributes<HTMLXdsInventoryLocationListElement>;
            "xds-inventory-service-list": LocalJSX.IntrinsicElements["xds-inventory-service-list"] & JSXBase.HTMLAttributes<HTMLXdsInventoryServiceListElement>;
        }
    }
}
